#!/bin/sh

if $(git diff --quiet); then
  echo "Compiling editor assets for production..."
  (cd editor && gulp prod) || exit 1
  git add -A editor/dist || exit 1
  git commit -m 'Recompile assets for deploy' # if it fails, that's because nothing changed

  git push origin master          || exit 1 # if everyone does this every time...
  git push truthmaker HEAD:master || exit 1 # ... this (the actual deploy) should be fast-forward
else
  echo "You cannot deploy, as you have changes in your local repository." >&2
  exit 1
fi
